spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.3.75:3306/dblog?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: 123456

# MyBatis
mybatis:
    type-aliases-package: com.rick.blogcore.persistence.beans
    mapper-locations: classpath:/com/rick/blogcore/persistence/mybatis/*.xml
# mapper
mapper:
    mappers:
        - com.rick.blogcore.plugin.BaseMapper
    not-empty: false
    identity: MYSQL
# pagehelper
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql